### ISSUE TITLE
Errors running `runCohortDiagnostics`

### ISSUE THREAD

**Issue by Jake-Gillberg** [ohdsi-studies/PioneerWatchfulWaiting#79] opened 2021-08-30 18:20 UTC
[console_log.txt](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/files/7078634/console_log.txt)

[console_log_errors.txt](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/files/7078647/console_log_errors.txt)

[sql_error.txt](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/files/7078649/sql_error.txt)

These errors are confounding me. Looks like it is propagating up from Cohort Diagnostics

**Comment by Jake-Gillberg** [comment] 2021-09-15 15:19
Was this the fix for the issue? https://github.com/ohdsi-studies/PioneerWatchfulWaiting/commit/65fd63d2758016329294e2e871c671204066fbc4

**Comment by keesvanbochove** [comment] 2021-09-16 12:53
@Jake-Gillberg thanks for following up, it looks like I was a bit too fast with closing this. I had assumed that it was related to #78 but looking at the error logs this seems to be a different issue. It seems the offending query is in https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/ComputeIncidenceRates.sql, so this would actually be an issue to raise in CohortDiagnostics instead. Could it be caused by invalid start or end dates in TMC_RED.dbo.observation_period? It's also possible that year_of_birth is null but judging by the SQL that should not throw an error although it may mess up the data.

**Comment by Jake-Gillberg** [comment] 2021-09-16 17:58
Any thoughts on if these errors have impacted the results we sent? The run was able to recover successfully after encountering them. I'll potentially be able to dig into this further next week

**Comment by keesvanbochove** [comment] 2021-10-01 22:10
I'm closing this issue here is is actually raised in CohortDiagnostics (see link above), so it should be filed there if it persists: https://github.com/OHDSI/CohortDiagnostics/issues.

To answer your last question: It would show up in the cohort diagnostics results as missing incidence rates for some cohorts, but this may not be a big deal (the cohort in the attached log, 301 is a strata cohort for EAU High Risk that isn't populated in many databases anyway). More problematic is that it stops the execution of cohort diagnostics as well, so the diagnostics results that you sent in are empty (the zip file is only a few KB).

There is a small chance that this problem was actually caused by some end dates that were before the start dates, which has been fixed in the newest release https://github.com/ohdsi-studies/PioneerWatchfulWaiting/releases/tag/v0.4.4 - maybe it's worth trying this version and see if the error persists?

**Closed by keesvanbochove** 2021-10-01 22:10 UTC
