### ISSUE TITLE
Shiny app issues

### ISSUE THREAD

**Issue by bdemeulder** [ohdsi-studies/PioneerWatchfulWaiting#34] opened 2021-05-19 11:28 UTC
Updates are needed in the shiny app for characterization: 

- Cohort.csv and cohortXref.csv have to be updated with the current list.
- Time to event tab initiates an empty plot only.
![shiny app time to event 19052021](https://user-images.githubusercontent.com/11734167/118805265-04d3bf80-b8a6-11eb-9bc2-e93d7415ce25.png)

- In both characterization and compare cohort char. tabs, the names of the cohorts are lost (e.g. attached).
![Shiny app 19052021](https://user-images.githubusercontent.com/11734167/118805124-d81fa800-b8a5-11eb-83a9-7038a4c7e40d.png)

**Comment by MaximMoinat** [comment] 2021-05-31 11:51
@bdemeulder I could not reproduce the last item by running the RShiny locally using the Task #3 Pre-merged data. So I expect that updating the RShiny app on the server will fix the issue.
![image](https://user-images.githubusercontent.com/17825660/120188954-0b075b80-c217-11eb-9128-735b9adbbc77.png)

**Comment by MaximMoinat** [comment] 2021-05-31 11:57
The first point, updating CohortsXref.csv should have been fixed with PR #31. Here also, I think updating the RShiny app on the [ShinyDeploy](https://github.com/OHDSI/ShinyDeploy/tree/master/PioneerWatchfulWaitingDiag). Last update there was 2 months ago.

I will close this issue and create separate issues.

**Closed by MaximMoinat** 2021-05-31 11:57 UTC
